### ISSUE TITLE
Bug select data source

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#15]
Pas create data source, bisa dibuat tanpa ada source yang dipilih. hasilnya running ga jelas
![issue008](https://user-images.githubusercontent.com/13661944/32206187-371ff874-be26-11e7-954e-30ec30691c40.png)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI](https://trello.com/c/BtGVtaia/102-fix-bug-ui)

**Comment by laxen00** [comment]
done, please check @syatriia

**Comment by syatriia** [comment]
still not fixed

![1](https://user-images.githubusercontent.com/13661944/32309992-ecf2a740-bfc1-11e7-98aa-8ddc088801be.jpg)
![2](https://user-images.githubusercontent.com/13661944/32309994-ee0c7a16-bfc1-11e7-8c91-8455a51bdbcc.jpg)

**Comment by laxen00** [comment]
@syatriia please check

**Comment by syatriia** [comment]
done
